### ISSUE TITLE
Tela de menu não aceita characteres acentuados.

### ISSUE THREAD

**Issue by victorperin** [ciencia-computacao-unip/APS_4#15]

**Comment by degrecci** [comment]
Só compilar usando 
javac Classe.java -encoding UTF-8  
Pode ser problema do editor de texto...

**Comment by degrecci** [comment]
http://imgur.com/ixLyvT5

**Comment by victorperin** [comment]
Usando windows e Sublime aqui...
O problema é o java mesmo que tenho que passar esse argumento... uhauhauha

**Comment by degrecci** [comment]
só compila com deste jeito ae então e ta sussa,ps:  entra slack tbm.
